/* Generated by Together */

package com.util.log4debug.impl;

import it.sella.util.Log4Debug;

public interface InternalLog4Debug extends Log4Debug {
public static final String AUTHOR="$Author: gbs00324 $";
public static final String REVISION="$Revision: 1.1 $";
public static final String DATE="$Date: 2008/03/19 12:12:24 $";
  void setLoggedClass( Class loggedClass);
  Object clone();
}
